accounts/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from django.views.generic import TemplateView
from . import views

app_name = 'accounts'

urlpatterns = [
    url(r"login/$", auth_views.LoginView.as_view(template_name="accounts/login.html"),name='login'),
    url(r"logout/$", auth_views.LogoutView.as_view(), name="logout"),
    url(r"signup/$", views.UserSignupView.as_view(), name="signup"),
    url(r"singup3/$", TemplateView.as_view(template_name="accounts/singup_complete.html"),name="signup3"),
    url(r"profile/(?P<username>[-\w]+)/$", views.UserTagsView.as_view(template_name="accounts/profile.html"), name="user_tags"),
    # url(r"profile2/(?P<username>[-\w]+)/$", views.UserTagsView.as_view(), name="user_tags"),
    url(r"profile/(?P<username>[-\w]+)/delete/(?P<slug>[-\w]+)$", views.UserTagDeleteView.as_view(), name="user_tag_delete"),
    url(r"profile/(?P<username>[-\w]+)/change-favourite-team/(?P<pk>\d+)/$", views.UserFavTeamChangeView.as_view(), name="change_fav_team"),
    url(r"profile/(?P<username>[-\w]+)/history/$", views.UserHistoryView.as_view(), name="user_history"),

]

news/urls.py
from django.conf.urls import url

from . import views
from django.views import generic

app_name = 'news'

urlpatterns = [
    url(r"^$", views.NewsListView.as_view(), name="all"),
    url(r"for/(?P<username>[-\w]+)/$", views.UserNewsListView.as_view(), name="for_user"),
    url(r"page/(?P<username>[-\w]+)/$", views.PageUserNewsView.as_view(), name="page_user"),
    url(r"player/(?P<slug>[-\w]+)/$", views.PlayerNewsView.as_view(), name="page_player"),
    url(r"^page/for2/(?P<username>[-\w]+)/$", generic.TemplateView.as_view(template_name="news/news_page.html"),name="testas2"),
    url(r"add/(?P<username>[-\w]+)/(?P<pk>\d+)/$", views.AddToNewsView.as_view(), name="add_to_post"),



]

simplesocial/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from . import views
from django.views import generic

urlpatterns = [
    url(r"^$", views.HomePage.as_view(), name="home"),
    url(r"^test/$", views.TestPage.as_view(), name="test"),
    url(r"^testas/$", generic.TemplateView.as_view(template_name="_test.html"),name="testas"),
    # url(r"^test/?search=(?P<search>[-\w]+)/$", generic.TemplateView.as_view(template_name="_test.html"),name="testas"),
    url(r"^thanks/$", views.ThanksPage.as_view(), name="thanks"),
    url(r"^admin/", admin.site.urls),
    url(r"^accounts/", include("accounts.urls", namespace="accounts")),
    url(r"^accounts/", include("django.contrib.auth.urls")),
    url(r"^posts/", include("posts.urls", namespace="posts")),
    url(r"^groups/",include("groups.urls", namespace="groups")),
    url(r"^news/",include("news.urls", namespace="news")),
    url(r"^tags/",include("tags.urls", namespace="tags")),
    url(r"^details/",include("stats.urls", namespace="stats")),
]

tags/urls.py
from django.conf.urls import url

from . import views
from django.views import generic
app_name = 'tags'

urlpatterns = [
    url(r"^$", generic.TemplateView.as_view(template_name="tags/_tags.html"),name="tags"),
    url(r"search/$",views.search_tags),
    url(r"tag_add/(?P<slug>[-\w]+)/(?P<negative>[-\w]+)/$",views.AddTagView.as_view(),name="tag_add"),
    url(r"tag_delete/(?P<slug>[-\w]+)/$",views.DeleteTagView.as_view(),name="tag_delete"),
    url(r"redirect/(?P<slug>[-\w]+)/$", views.RedirectTagView.as_view(), name="tag_redirect"),
    url(r"(?P<slug>[-\w]+)/$", views.TagsNewsListView.as_view(), name="tags_news"),


    # url(r"tag_ad/(?P<slug>[-\w]+)/$",views.AddTag.as_view(),name="tag_ad"),


]

accounts/models.py
from django.contrib import auth
from django.db import models
from django.utils import timezone
from tags.models import Team, Tags , League


class User(auth.models.User, auth.models.PermissionsMixin):
    pass
    # def __str__(self):
    #     return "@{}".format(self.username)




class UserProfile(models.Model):


    UserProfile = models.OneToOneField(auth.models.User,default=1)
    fav_team = models.ForeignKey(Team,default=1,related_name='favteams')
    tags=models.ManyToManyField(Tags,through='UserTags')

    def __str__(self):
        return "{}".format(self.UserProfile)

class UserTags(models.Model):
    user=models.ForeignKey(UserProfile,related_name="usertags")
    tag=models.ForeignKey(Tags)
    negative=models.BooleanField(default=False)

    def __str__(self):
        return "{}_{}".format(self.user,self.tag.pk)

    class Meta:
        unique_together = ("tag", "user")

news/models.py
from django.db import models
from django.utils.text import slugify
from accounts.models import UserProfile
from django.contrib.auth import get_user_model
from tags.models import Tags, Team, NewsPaper
User = get_user_model()

from django.conf import settings
# Create your models here.



class News(models.Model):
    title= models.CharField(max_length=50, unique=True)
    text= models.CharField(max_length=2000)
    news_url= models.URLField(max_length=250)
    image=models.ImageField(blank=True,null=True)
    image_url=models.URLField(blank=True,null=True)
    tweet=models.BooleanField(default=False)
    social_source=models.CharField(max_length=100,blank=True)
    fb_post=models.BooleanField(default=False)
    meme=models.BooleanField(default=False)
    source=models.ForeignKey(NewsPaper,related_name='newspapers',null=True,blank=True)
    team=models.ManyToManyField(Team,through='NewsTeam')
    date_added=models.DateTimeField()
    date_crawled=models.DateTimeField(auto_now=True)
    users=models.ManyToManyField(UserProfile,through='UserViewedNews')
    news_tags=models.ManyToManyField(Tags,through='NewsTags')
    favs=models.IntegerField(blank=True,null=True)
    retweets=models.IntegerField(blank=True,null=True)
    replies=models.IntegerField(blank=True,null=True)
    fb_rating = models.IntegerField(blank=True,null=True)

    def __str__(self):
        return self.title


    class Meta:
        ordering = ["-date_added"]

class NewsTeam(models.Model):
    news=models.ForeignKey(News,related_name="newsteams")
    team=models.ForeignKey(Team,related_name='teamnews')

    def __str__(self):
        return "{}_{}".format(self.news.pk,self.team.name)

    class Meta:
        unique_together = ("news", "team")

class UserViewedNews(models.Model):
    user=models.ForeignKey(UserProfile,related_name="usernews")
    news=models.ForeignKey(News,related_name="newsuser")
    created_at=models.DateTimeField(auto_now=True)

    def __str__(self):
        return "{}_{}".format(self.user,self.news.title[:10])

    class Meta:
        unique_together = ("news", "user")


class NewsTags(models.Model):
    news=models.ForeignKey(News,related_name="newstags")
    tag=models.ForeignKey(Tags)

    def __str__(self):
        return "{}_{}".format(self.news.pk,self.tag.tag_name)
    class Meta:
        unique_together = ("tag", "news")

accounts/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm
from accounts import models
from django import forms
from betterforms.multiform import MultiModelForm, MultiForm


class UserCreateForm(UserCreationForm):

    class Meta:
        fields = ("username", "email", "password1", "password2")
        model = get_user_model()

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["username"].label = "Display name"
        self.fields["email"].label = "Email address"

class UserUpdateForm(forms.ModelForm):
    class Meta:
        fields= ('fav_team',)
        model = models.UserProfile

class UserCreationMultiForm(MultiModelForm):
    form_classes = {
        'user': UserCreateForm,
        'profile': UserUpdateForm,
    }
    def save(self, commit=True):
        objects = super(UserCreationMultiForm, self).save(commit=False)

        if commit:
            user = objects['user']
            user.save()
            profile = objects['profile']
            profile.UserProfile = user
            profile.save()

        return objects

accounts/views.py
from django.contrib.auth import login, logout
from django.core.urlresolvers import reverse_lazy
from django.views.generic import CreateView, ListView, RedirectView, UpdateView
from django.shortcuts import redirect, reverse
from django.contrib.auth.models import User
from django.contrib import messages
from django.contrib.auth.mixins import(
    LoginRequiredMixin,
    PermissionRequiredMixin
)

from . import forms
from tags.models import Tags
from accounts.models import UserTags,UserProfile
from news.models import News, UserViewedNews
from django.http import Http404

class SignUp(CreateView):
    form_class = forms.UserCreateForm
    success_url = reverse_lazy("accounts:signup2")
    template_name = "accounts/signup.html"

class UpdateProfile(CreateView):
    form_class = forms.UserUpdateForm
    success_url = reverse_lazy("accounts:signup3")
    template_name = "accounts/signup2.html"



class UserSignupView(CreateView):
    form_class = forms.UserCreationMultiForm
    success_url = reverse_lazy('accounts:signup3')
    template_name = "accounts/signup.html"

    # def form_valid(self, form):
    #     # Save the user first, because the profile needs a user before it
    #     # can be saved.
    #     user = form['user'].save()
    #     profile = form['profile'].save(commit=False)
    #     profile.UserProfile = user
    #     profile.save()
    #     return redirect(self.get_success_url())


class UserTagsView(LoginRequiredMixin, ListView):
    model=UserTags
    template_name="accounts/_user_tags_list.html"



    def get_queryset(self):
        try:
            self.user_now=self.kwargs.get("username")

            userprofile_id = UserProfile.objects.filter(UserProfile__username=self.user_now)[0].id
            self.tags = UserTags.objects.filter(user_id=userprofile_id).order_by("negative","tag__tag_name")
            # self.tags = self.tags[0].tag.tag_name
            # self.tags = Tags.objects.filter(userprofile__id=userprofile_id).order_by("tag_name")


        except UserTags.DoesNotExist:
            raise Http404
        else:
            return self.tags
    def get_context_data(self, **kwargs):
            context = super().get_context_data(**kwargs)
            context["tags"] = self.tags
            return context



class UserTagDeleteView(LoginRequiredMixin,RedirectView):

    def get(self, request, *args, **kwargs):
            user_tags = UserTags.objects.filter(
                user=self.request.user.userprofile,
                tag__slug=self.kwargs.get("slug")
            ).get()

            user_tags.delete()
            messages.success(
                self.request,
                "You have successfully delete this tag."
            )
            return super().get(request, *args, **kwargs)

    def get_redirect_url(self, *args, **kwargs):
        return reverse("accounts:user_tags",kwargs={"username": self.kwargs.get("username")})
class UserHistoryView(LoginRequiredMixin,ListView):
    model=UserViewedNews
    template_name="accounts/user_history.html"

    def get_queryset(self):
        try:
            self.user_now=self.kwargs.get("username")
            userprofile_id = UserProfile.objects.filter(UserProfile__username=self.user_now)[0].id
            self.news_list = UserViewedNews.objects.filter(user__id=userprofile_id).order_by('created_at')
            # self.news_list = News.objects.filter(users__id=userprofile_id)

        except:
            raise Http404
        else:
            return self.news_list
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["news_list"] = self.news_list
        return context

class UserFavTeamChangeView(LoginRequiredMixin, UpdateView):
    form_class = forms.UserUpdateForm
    model = UserProfile

    template_name = "accounts/_user_fav_team.html"

    def get_success_url(self):
        return reverse_lazy("accounts:user_tags",kwargs={"username": self.kwargs.get("username")})

    # def form_valid(self, form):
    #     # Save the user first, because the profile needs a user before it
    #     # can be saved.
    #     fav_team = form['fav_team']
    #     UserP=self.request.user.userprofile
    #     profile.UserProfile = user
    #     profile.save()
    #     return redirect(self.get_success_url())

# class UserTeams(LoginRequiredMixin,CreateView):
#     pass

accounts/templates/accounts/_user_fav_team.html
{% block content %}
<div class="container">
    <h1>Change your favourite team</h1>
    <form method="POST">
        {% csrf_token %}
          <p>{{ form.as_p }}</p>

        <input type="submit" value="Submit" class="btn btn-default">
    </form>
</div>
{% endblock %}

accounts/templates/accounts/_user_tags_list.html
{% if tags.all%}
  <table class=tags_table>
  <tr>
    <h3>Favourite tags</h3>
  </tr>
  {% for tag in tags %}
    {% if not tag.negative %}
      {% if user.userprofile.fav_team.name != tag.tag.tag_name%}
        <tr>
          <td><a href="{% url 'tags:tags_news' slug=tag.tag.slug %}">{{tag.tag.tag_name}}</a></td>
          <td><a href="{% url 'accounts:user_tag_delete' username=user.username slug=tag.tag.slug %}">Delete</a></td>

        </tr>
        {% endif %}
    {% endif %}
  {% endfor %}
  </table>
  <table class=tags_table>
  <tr>
    <h3>"Not interested" tags</h3>
  </tr>
  {% for tag in tags %}
    {% if tag.negative %}
      {% if user.userprofile.fav_team.name != tag.tag.tag_name%}
        <tr>
          <td><a href="{% url 'tags:tags_news' slug=tag.tag.slug %}">{{tag.tag.tag_name}}</a></td>
          <td><a href="{% url 'accounts:user_tag_delete' username=user.username slug=tag.tag.slug %}">Delete</a></td>

        </tr>
      {% endif %}
    {% endif %}
  {% endfor %}
  </table>
{% else %}
<p>You haven't add additional tags yet. Please use search engine to add them.</p>
{% endif %}

accounts/templates/accounts/login.html
{% extends "base.html" %}
{% load bootstrap3 %}

{% block content %}
<div class="container">
    <h1>Login</h1>
    <form method="POST">
        {% csrf_token %}
        {% bootstrap_form form %}
        <input type="submit" value="Login" class="btn btn-default">
    </form>
</div>
{% endblock %}

accounts/templates/accounts/profile.html
<h3>Hi {{user.username}}</h3>
<h2>Favourite team: {{user.userprofile.fav_team}}</h2>
<a href="{% url 'accounts:change_fav_team' username=user.username pk=user.userprofile.id %}">change_fav_team</a>
<a href="{% url 'accounts:user_history' username=user.username %}"><h2>History</h2></a>
<h2>Your tags</h2>

{%include "accounts/_user_tags_list.html"%}

accounts/templates/accounts/signup.html
<!-- {% extends "base.html" %} -->
<!-- {% load bootstrap3 %} -->


{% block content %}
<div class="container">
    <h1>Sign Up</h1>
    <form method="POST">
        {% csrf_token %}
          <p>{{ form.as_p }}</p>

        <input type="submit" value="Sign Up" class="btn btn-default">
    </form>
</div>
{% endblock %}

accounts/templates/accounts/signup2.html
{% extends "base.html" %}
{% load bootstrap3 %}


{% block content %}
<div class="container">
    <h1>Select yout favourite team</h1>
    <form method="POST">
        {% csrf_token %}
        {% bootstrap_form form %}
        <input type="submit" value="Sign Up" class="btn btn-default">
    </form>
</div>
{% endblock %}

accounts/templates/accounts/singup_complete.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>brawo</title>
    <h1>Udało się</h1>
  </head>
  <body>

  </body>
</html>

accounts/templates/accounts/user_history.html
<h3>{{user.username}} history</h3>
{% if news_list.all%}


  {% for news in news_list %}
      <p><a href="{{ news.news.news_url }}">{{news.news.title}}</a></p>

  {% endfor %}
{% else %}
<p>You haven't seen any news yet.</p>
{% endif %}