accounts/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from django.views.generic import TemplateView
from . import views

app_name = 'accounts'

urlpatterns = [
    url(r"login/$", auth_views.LoginView.as_view(template_name="accounts/login.html"),name='login'),
    url(r"logout/$", auth_views.LogoutView.as_view(), name="logout"),
    url(r"signup/$", views.UserSignupView.as_view(), name="signup"),
    url(r"singup3/$", TemplateView.as_view(template_name="accounts/singup_complete.html"),name="signup3"),
    url(r"profile/(?P<username>[-\w]+)/$", views.UserTagsView.as_view(template_name="accounts/profile.html"), name="user_tags"),
    # url(r"profile2/(?P<username>[-\w]+)/$", views.UserTagsView.as_view(), name="user_tags"),
    url(r"profile/(?P<username>[-\w]+)/delete/(?P<slug>[-\w]+)$", views.UserTagDeleteView.as_view(), name="user_tag_delete"),
    url(r"profile/(?P<username>[-\w]+)/change-favourite-team/(?P<pk>\d+)/$", views.UserFavTeamChangeView.as_view(), name="change_fav_team"),
    url(r"profile/(?P<username>[-\w]+)/history/$", views.UserHistoryView.as_view(), name="user_history"),

]

news/urls.py
from django.conf.urls import url

from . import views
from django.views import generic

app_name = 'news'

urlpatterns = [
    url(r"^$", views.NewsListView.as_view(), name="all"),
    url(r"for/(?P<username>[-\w]+)/$", views.UserNewsListView.as_view(), name="for_user"),
    url(r"page/(?P<username>[-\w]+)/$", views.PageUserNewsView.as_view(), name="page_user"),
    url(r"player/(?P<slug>[-\w]+)/$", views.PlayerNewsView.as_view(), name="page_player"),
    url(r"^page/for2/(?P<username>[-\w]+)/$", generic.TemplateView.as_view(template_name="news/news_page.html"),name="testas2"),
    url(r"add/(?P<username>[-\w]+)/(?P<pk>\d+)/$", views.AddToNewsView.as_view(), name="add_to_post"),



]

posts/urls.py
from django.conf.urls import url

from . import views

app_name='posts'

urlpatterns = [
    url(r"^$", views.PostList.as_view(), name="all"),
    url(r"new/$", views.CreatePost.as_view(), name="create"),
    url(r"by/(?P<username>[-\w]+)/$",views.UserPosts.as_view(),name="for_user"),
    url(r"by/(?P<username>[-\w]+)/(?P<pk>\d+)/$",views.PostDetail.as_view(),name="single"),
    url(r"delete/(?P<pk>\d+)/$",views.DeletePost.as_view(),name="delete"),
]

simplesocial/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from . import views
from django.views import generic

urlpatterns = [
    url(r"^$", views.HomePage.as_view(), name="home"),
    url(r"^test/$", views.TestPage.as_view(), name="test"),
    url(r"^testas/$", generic.TemplateView.as_view(template_name="_test.html"),name="testas"),
    # url(r"^test/?search=(?P<search>[-\w]+)/$", generic.TemplateView.as_view(template_name="_test.html"),name="testas"),
    url(r"^thanks/$", views.ThanksPage.as_view(), name="thanks"),
    url(r"^admin/", admin.site.urls),
    url(r"^accounts/", include("accounts.urls", namespace="accounts")),
    url(r"^accounts/", include("django.contrib.auth.urls")),
    url(r"^posts/", include("posts.urls", namespace="posts")),
    url(r"^groups/",include("groups.urls", namespace="groups")),
    url(r"^news/",include("news.urls", namespace="news")),
    url(r"^tags/",include("tags.urls", namespace="tags")),
    url(r"^details/",include("stats.urls", namespace="stats")),
]

tags/urls.py
from django.conf.urls import url

from . import views
from django.views import generic
app_name = 'tags'

urlpatterns = [
    url(r"^$", generic.TemplateView.as_view(template_name="tags/_tags.html"),name="tags"),
    url(r"search/$",views.search_tags),
    url(r"tag_add/(?P<slug>[-\w]+)/(?P<negative>[-\w]+)/$",views.AddTagView.as_view(),name="tag_add"),
    url(r"tag_delete/(?P<slug>[-\w]+)/$",views.DeleteTagView.as_view(),name="tag_delete"),
    url(r"redirect/(?P<slug>[-\w]+)/$", views.RedirectTagView.as_view(), name="tag_redirect"),
    url(r"(?P<slug>[-\w]+)/$", views.TagsNewsListView.as_view(), name="tags_news"),


    # url(r"tag_ad/(?P<slug>[-\w]+)/$",views.AddTag.as_view(),name="tag_ad"),


]

templates/_test.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
  <head>
    <meta charset="utf-8">
    <title>asdas</title>

  </head>


  <body>

<blockquote class="twitter-tweet" data-lang="en"><p lang="en" dir="ltr">Health care has always been about something bigger than politics: it's about the character of our country. <a href="https://t.co/UqLO14Hef7">https://t.co/UqLO14Hef7</a></p>&mdash; Barack Obama (@BarackObama) <a href="https://twitter.com/BarackObama/status/877974755592228868">22 czerwca 2017</a></blockquote>
<blockquote class="twitter-tweet" data-lang="pl"><p lang="en" dir="ltr">On this National Gun Violence Awareness Day, let your voice be heard and show your commitment to reducing gun violence. <a href="https://t.co/eXkV4WmkqA"></a></p>&mdash; Barack Obama (@BarackObama) <a href="https://twitter.com/BarackObama/status/870695481290117120">2 czerwca 2017</a></blockquote>
<blockquote class="twitter-tweet" data-lang="pl"><p lang="en" dir="ltr">VIDEO: Love this! Arsene Wenger recalls shock announcement of Sol Campbell&#39;s move from Spurs. <a href="https://twitter.com/hashtag/afc?src=hash">#afc</a> <a href="https://t.co/Ix1GrNtiJT">pic.twitter.com/Ix1GrNtiJT</a></p>&mdash; ArsenalCentral (@AFCCentralHQ) <a href="https://twitter.com/AFCCentralHQ/status/883085540970647554">6 lipca 2017</a></blockquote>
<iframe src="https://www.facebook.com/plugins/post.php?href=https%3A%2F%2Fwww.facebook.com%2FArsenalTSN%2Fposts%2F1606065339418035%3A0&width=500" width="500" height="468" style="border:none;overflow:hidden" scrolling="no" frameborder="0" allowTransparency="true"></iframe>
<iframe src="https://www.facebook.com/plugins/post.php?href=https%3A%2F%2Fwww.facebook.com%2FSarcasticGooner%2Fposts%2F1959833417587321%3A0&width=500" width="500" height="500" style="border:none;overflow:hidden" scrolling="no" frameborder="0" allowTransparency="true"></iframe>
<script async src="//platform.twitter.com/widgets.js" charset="utf-8"></script>
<script async src="//platform.twitter.com/widgets.js" charset="utf-8"></script>
<script async src="//platform.twitter.com/widgets.js" charset="utf-8"></script>
<script async src="//platform.twitter.com/widgets.js" charset="utf-8"></script>

  </body>
</html>

templates/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
  <head>
    <meta charset="utf-8">
    <title>Star Social</title>
    <!-- Latest compiled and minified CSS -->
    <script src="https://code.jquery.com/jquery-3.2.1.min.js" integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4=" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js" integrity="sha256-T0Vest3yCU7pafRw9r+settMBX6JkKN06dqBnpQ8d30=" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>



    <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet">
    <script type="text/javascript">
    $(function(){

        $('#search').keyup(function(){
            console.log("dziala");
            $.ajax({
                type: "POST",
                url: "/tags/search/",
                data: {
                    'search_text': $('#search').val(),
                    'csrfmiddlewaretoken' : $("input[name=csrfmiddlewaretoken]").val()
                },
                success: searchSuccess,
                dataType: 'html'

            });

        });
    });
    function searchSuccess(data, textStatus, jqXHR)
    {
        $('#search-results').html(data);
    }
    function slugify(text)
      {
        return text.toString().toLowerCase()
          .replace(/\s+/g, '-')           // Replace spaces with -
          .replace(/[^\w\-]+/g, '')       // Remove all non-word chars
          .replace(/\-\-+/g, '-')         // Replace multiple - with single -
          .replace(/^-+/, '')             // Trim - from start of text
          .replace(/-+$/, '');            // Trim - from end of text
      }
      $(document).ready(function() {
        $("#search").keydown(function(event){
          if(event.keyCode == 13) {
            event.preventDefault();
            generateUrl()
          return false;
      }
      });
    });
    function generateUrl(){
      console.log("cos")
	     var x = document.querySelector("[list='search-results']").value.toString().toLowerCase()
         .replace(/\s+/g, '-')           // Replace spaces with -
         .replace(/[^\w\-]+/g, '')       // Remove all non-word chars
         .replace(/\-\-+/g, '-')         // Replace multiple - with single -
         .replace(/^-+/, '')             // Trim - from start of text
         .replace(/-+$/, '');

      var link= "{% url 'tags:tag_redirect' slug='tmp' %}";
      link = link.replace('tmp', x)
      if(x.length>0){
        window.location.href = link;
      }

       document.querySelector("[list='search-results']").value="";
      //  window.location.href = "/tags/"+x;


       }

    </script>
    <style>
    input::-webkit-calendar-picker-indicator {
      display: none;
    }
    </style>
  </head>


  <body>

    <nav class="navbar  mynav" role="navigation" id="navbar">
    			<div class="container">

            <a class="navbar-brand mynav" href="{% url 'home' %}">Star Social</a>

            <!-- <input type="text" id="id_input"> -->
            <datalist id="search-results">

            </datalist>
    					<ul class="nav navbar-nav navbar-right">
    						{% if user.is_authenticated %}
                      <li>
                      <div class="col-lg-4">
                      <div class="input-group">

                      <form name="leform" onsubmit="return generateLink();">
                        {% csrf_token %}
                      <input type="text" class="form-control" id="search"  name="search" list="search-results" placeholder="Search tags" >
                      <span class="input-group-btn">
                          <button class="btn btn-default" type="button" id="search-btn" onclick="generateUrl()">Go!</button>
                      </span>
                      </div>
                      </div>
                      </li>
                      <li><a href="{% url 'posts:create' %}" class="btn btn-simple">Post</a></li>
                      <li><a href="{% url 'groups:all' %}" class="btn btn-simple">Groups</a></li>
                      <li><a href="{% url 'news:for_user' username=user.username %}" class="btn btn-simple">News</a></li>
                      <!-- <li><a href="{% url 'news:all' %}" class="btn btn-simple">News</a></li> -->
                      <li><a href="{% url 'groups:create' %}" class="btn btn-simple">Create Group</a></li>
                      <li><a href="{% url 'accounts:user_tags' username=user.username %}" class="btn btn-simple">Profile</a></li>
                      <li><a href="{% url 'accounts:logout' %}" class="btn btn-simple">Log out</a></li>
    						{% else %}
    						      <li><a href="{% url 'groups:all' %}"class="btn btn-simple">Groups</a></li>
                      <li><a href="{% url 'news:all' %}" class="btn btn-simple">News</a></li>
    						      <li><a href="{% url 'accounts:login' %}" class="btn btn-simple">Log in</a></li>
    						      <li><a href="{% url 'accounts:signup' %}" class="btn btn-simple">Sign up</a></li>
    						{% endif %}
    					</ul>



    			</div>
    		</nav>
        <div class="container mycontent">
          {% block content %}

          {% endblock %}

        </div>



<canvas id="canvas"></canvas>



  </body>

</html>

templates/index.html
{% extends "base.html" %}
{% block content %}

    <h1>Welcome to Star Social!</h1>
    <h2>The best community for all things on outer space!</h2>
    <h2>Login or Sign-up for free to get started!</h2>


{% endblock %}

templates/test.html
{% extends "base.html" %}
{% block content %}
<div class="container">
  <h1>You are now logged in!</h1>
  <h2><a href="{% url 'groups:all'%}">Go to Groups</a></h2>


</div>




{% endblock %}

templates/test2.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
  <head>
    <meta charset="utf-8">
    <title>asdas</title>
    <link rel="stylesheet" href="http://code.jquery.com/ui/1.8.18/themes/base/jquery-ui.css" type="text/css" media="all" />
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js" type="text/javascript"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.8.16/jquery-ui.min.js" type="text/javascript"></script>

    <script type="text/javascript">
        $(document).ready(function(){
            var location_input=$('input[id="autocomplete-city"]');
            location_input.autocomplete({
              source: "/api/get_city_names/",
              minLength: 2
            });
          } );

        //   keeps same width as box
          jQuery.ui.autocomplete.prototype._resizeMenu = function () {
              var ul = this.menu.element;
              ul.outerWidth(this.element.outerWidth());
            }
    </script>

  </head>


  <body>
    <div class="ui-widget">
      <label for="cities">City: </label>
      <input id="autocomplete-city">
    </div>

  </body>
</html>

templates/thanks.html
{% extends "base.html" %}
{% block content %}
<h1>Thanks for visiting! Come back soon!</h1>

{% endblock %}